# library("sgejobs")
# sgejobs::job_single(
#     "mostafavi",
#     create_shell = TRUE,
#     queue = "bluejay",
#     memory = "20G",
#     command = "Rscript 01_SST_rnascope.R",
#     create_logdir = TRUE
# )

# log-transformation before taking the mean is
# always better than the opposite way
#https://rpubs.com/hrlai/meanlog_logmean


#### load relevant packages ####

library("readr")
library("sessioninfo")
library("here")
library("dplyr")
library("purrr")
library("zoo") #fill forward NA values in subject_id column

#### load data generated by prism ####

data_dir <- here("raw-data", "rnascope_data_from_prism",
                 "SST_Raw.csv")
sst <- read_csv(file = data_dir)

#### clean columns ####
sst$subject_id <- sst$`...1`
sst <- sst |> select(-c("...2", "...1"))


# head(sst_raw)
# `0-21.25` `21.25-42.5` `42.5-63.75` `63.75-85` `85-106.25` `106.25-127.5` `127.5<x` subject_id
# <dbl>        <dbl>        <dbl>      <dbl>       <dbl>          <dbl>     <dbl> <chr>
# 1         1           16           68         11           8             10        31 Br3854
# 2         2            4           73         11           1              1         2 NA
# 3        56            5            5         15           1              1         2 NA
# 4         2            1           32         60           1             18         6 NA
# 5        14           38            1          7          11              1         1 NA
# 6         3            9            1          1           1              1         9 NA

# > unique(sst_raw$subject_id)
# [1] "Br3854" "Br3873" "Br3880" "Br8549"

# find all non-NA values in subject_id row
which(!is.na(sst$subject_id))
#[1]     1  5831 10904 20841

## fill subject_id column
sst$subject_id <- zoo::na.locf(sst$subject_id)

## log2(x+1) conversion across all columns
sst |> log2(sst$`0-21.25` + 1)
sst_log <- sst |> mutate(across(-c("subject_id"), function(x) log2(x+1)))

# > head(sst_log)
# # A tibble: 6 × 8
# `0-21.25` `21.25-42.5` `42.5-63.75` `63.75-85` `85-106.25` `106.25-127.5` `127.5<x` subject_id
# <dbl>        <dbl>        <dbl>      <dbl>       <dbl>          <dbl>     <dbl> <chr>
#     1      1            4.09         6.11       3.58        3.17           3.46      5    Br3854
# 2      1.58         2.32         6.21       3.58        1              1         1.58 Br3854
# 3      5.83         2.58         2.58       4           1              1         1.58 Br3854
# 4      1.58         1            5.04       5.93        1              4.25      2.81 Br3854
# 5      3.91         5.29         1          3           3.58           1         1    Br3854
# 6      2            3.32         1          1           1              1         3.32 Br3854


